### ISSUE TITLE
Support for utländsk ägare etc

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo-server#1]
If there is no data in Person or Organinsation in Inskrivning the data is in InskrivenPerson. That could be uländsk ägare or skyddad identitet.

**Comment by mulfvik** [comment]
Fnr examples:

Utländsk ägare: 040178437
Person ägare: 040178436
Organisation ägare: 040100003
Organistation ägare: 040094630
Skyddad identitet: 040165532

**Comment by afogelberg** [comment]
Fixed with #15
