### ISSUE TITLE
"Creating a duplicate database object for the same connection"

### ISSUE THREAD

**Issue by Grammostola** [origo-map/origo-server#102]
Latest Origo server, setup search/ , search for something twice and this appears in the log:

>WARNING: Creating a duplicate database object for the same connection.
    at Object.pgConnect [as pg] (C:\kod\origo-server-up\lib\pg.js:21:18)

https://github.com/vitaly-t/pg-promise/wiki/FAQ#warning-creating-a-duplicate-database-object-for-the-same-connection 
says to create one database object and reuse it.
> If you ever see this warning, rectify your Database object initialization, so there is only one object per connection details.

This is probably part of the idea behind connectionexists.js however that check seems to always return false because after a config is added to the connections array it gets additional attributes.

It's not yet entirely clear to me in what instances the database object normally needs recreating.
> Note however, that in special cases you may need to re-create the database object, if its connection pool has been shut-down externally. And in this case the library won't be showing any warning.

The warning goes away if one rearranges pg.js like so:
```javascript
var pgConnect = function(res, queries, dbConfig) {
  
  if (!connections.length) {
    var config = {
      user: dbConfig.user,
      password: dbConfig.password,
      host: dbConfig.connectString,
      port: dbConfig.port,
      database: dbConfig.database
    };
      var connection = pg(config);
      connections.push({
        config: config,
        connection: connection
      });
    } else {
      var connection = connections[0].connection
    }
```

which is to say ignore connectionexists and only create one db object...which seems to work without warnings for me in a dev environ with two tabs and search-spamming but over time with more users and this setup might not be feasible.

Something should probably be done about the warning at any rate, I have received feedback of at least one other setup that saw it and currently believe it to be somewhat reproducible.

Edit. The terminology is slightly confusing. pg-promises' documentation says 'database object per connection details' and in the origo server code a "connection" is a database object.

**Comment by Grammostola** [comment]
Yes, looking at it further and testing some I think the db object "connection" should be created at startup of origo server (if search is configured) and never again. If the postgresql service is stopped and search attempts are made they fail, of course, but the pg promise db object is still live and search results are available again when the postgresql service is started anew. This rhymes with http://vitaly-t.github.io/pg-promise/Database.html so I'll try and fixup a PR. (Creating multiple database objects and as such multiple connection pools is probably a waste of resources, hence the warning message from pg-promise)

**Comment by MattiasSp** [comment]
Great work! We also noticed these warnings, but so far weren't able to put in the time to research the issue.

**Comment by Jonas074** [comment]
Any progress on this?

**Comment by Grammostola** [comment]
Hi, well linked PR updates dependancies which makes connectionexists work again and as such this issue's warnings go away because duplicate db objects aren't created anymore, however as mentioned in that PR and above the real issue might be what use connectionexists serves. I'll see about getting that PR merged and then about creating a new issue about connectionexists.
