### ISSUE TITLE
Search addresses with gardsadressomrade fail

### ISSUE THREAD

**Issue by Owemyr** [origo-map/origo-server#121]
When searching addresses with gardsadressomrade (missing adressomrade) origo-server fail with this error:

`TypeError: Cannot read properties of undefined (reading 'faststalltNamn')
    at origo-server\handlers\lmsearchaddress.js:278:62
    at Array.forEach (<anonymous>)
    at concatResult (origo-server\handlers\lmsearchaddress.js:268:12)
    at origo-server\handlers\lmsearchaddress.js:183:16`

Used this to fix:
```
let faststalltNamn = '';
    if ('gardsadressomrade' in feature.properties) {
      faststalltNamn = feature.properties.gardsadressomrade.adressomrade.faststalltNamn + ' ' + feature.properties.gardsadressomrade.faststalltNamn;
    }
    else {
      faststalltNamn = feature.properties.adressomrade.faststalltNamn;
    }
```

**Comment by johnnyblasta** [comment]
Do you have a example of a address I can test with?

**Comment by Owemyr** [comment]
For exemple if you search for "huleg...", seems like a lot of addresses use gårdsadressområde, at least in Västra götaland.
