### ISSUE TITLE
Change default geometryField value

### ISSUE THREAD

**Issue by markus659** [origo-map/origo-server#19]
Currently the default value is "SHAPE" for the geometryField for MS SQL, Oracle and Postgres. I reckon we should change it to "geom", at least for postgres as I think this is the most common, I'm not sure about the others.

https://github.com/origo-map/origo-server/blob/eb10404a078f3e06ee3392fa052fbbf3b9ebce23/models/mssqldefault.js#L8

https://github.com/origo-map/origo-server/blob/eb10404a078f3e06ee3392fa052fbbf3b9ebce23/models/oracledefault.js#L7

https://github.com/origo-map/origo-server/blob/427c78756c27427d2a82772013f0e3847989f523/models/pgdefault.js#L8

**Comment by afogelberg** [comment]
Good idea @markus659

**Comment by markus659** [comment]
Fixed with https://github.com/origo-map/origo-server/commit/1440a658743f47b0a719e50a1762dcd3c600d7aa.
