### ISSUE TITLE
Excel export

### ISSUE THREAD

**Issue by asemoller** [origo-map/origo-server#41]
Add possibility to export selected features from origo-map as an excel file. This function is needed if using the simple export function in the forthcoming info window.

**Comment by tonnyandersson** [comment]
It would be nice if such a function were made as generic as possible, i.e. that the Origo Server part is not specifically built with the selection tool in mind, but rather as a generic export-to-Excel function. It should be possible to pass "any" type of table data to the function for export to Excel.

**Comment by asemoller** [comment]
I agree, that's the intention!

Please give us some useful user cases for this function.
